# Site settings
name: Shikhar Gupta
title: Shikhar Gupta
author: "Shikhar Gupta"
permalink: /:title/
description: AI Enthusiast and Software Developer
url: https://shikhargupta.github.io/
baseurl: ''
email: guptashikhar20@gmail.com
cover: https://shikhargupta.github.io/img/og.png
logo: https://shikhargupta.github.io/img/emojis/technologist.png
resume: https://shikhargupta.github.io/resume.pdf
excerpt_separator: "\n\n\n"
minimal: true
mathjax: true

social:
  - title: email
    url: mailto:guptashikhar20@gmail.com
  - title: github
    url: https://github.com/shikhargupta
  - title: linkedin
    url: https://www.linkedin.com/in/gshikhar02/

navigation:
  - {title: Mail, icon: envelope, url: "mailto:niklasbuschmann@users.noreply.github.com"}
  - {title: Github, icon: github, url: "https://github.com/niklasbuschmann/"}
  - {title: Feed, icon: rss, url: "/feed.xml"}

remote_theme: niklasbuschmann/contrast

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
  - jekyll-feed
