# Site settings
name: Shikhar Gupta
title: Shikhar Gupta
author: "Shikhar Gupta"
permalink: /:title/
description: "Made with <b style=\"color: #f45;\">&lt;3</b>"
url: https://shikhargupta.github.io/
baseurl: ''
email: guptashikhar20@gmail.com
cover: https://shikhargupta.github.io/img/og.png
logo: https://shikhargupta.github.io/img/emojis/technologist.png
resume: https://shikhargupta.github.io/resume.pdf
excerpt_separator: "\n\n\n"
minimal: true
mathjax: true

social:
  - title: email
    url: mailto:guptashikhar20@gmail.com
  - title: github
    url: https://github.com/shikhargupta
  - title: linkedin
    url: https://www.linkedin.com/in/gshikhar02/

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "blog.html"}
  - {file: "README.md"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:guptashikhar20@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/Shikhargupta"}

comments:
 disqus_shortname: "https-shikhargupta-github-io-blog"    # see https://disqus.com/

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
  - jekyll-feed
