# Site settings
name: Shikhar Gupta
title: Shikhar Gupta
description: AI enthusiast and software developer
url: https://shikhargupta.github.io/
baseurl: ''
email: guptashikhar20@gmail.com
cover: https://shikhargupta.github.io/img/og.png
logo: https://shikhargupta.github.io/img/emojis/technologist.png
resume: https://shikhargupta.github.io/resume.pdf
social:
  - title: email
    url: mailto:guptashikhar20@gmail.com
  - title: github
    url: https://github.com/shikhargupta
  - title: linkedin
    url: https://www.linkedin.com/in/gshikhar02/

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
